apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-ps-deploy
  labels:
    app: wisecow-ps-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow-ps-app
  template:
    metadata:
      labels:
        app: wisecow-ps-app
    spec:
      containers:
      - name: wisecow-ps-container
        image: prathamesh78/wisecow
        ports:
        - containerPort: 4499
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-ps-np-service
  labels:
    app: wisecow-ps-app
spec:
  selector:
    app: wisecow-ps-app

  type: NodePort
  ports:
  - nodePort: 4499    
    port: 4499
    targetPort: 4499
